#-------------------------------------------------------------------------#
#-------------------------- TOBIAS input data ----------------------------#
#-------------------------------------------------------------------------#

data:
  Cave: [data/PA*bam]                                   #list of .bam-files
  Surface: [data/SF*.bam]  #list of .bam-files
  
run_info:
  organism: astyanax                           #mouse/human
  fasta: data/AstMex_v2_fixed_names.fa            #.fasta-file containing organism genome
  blacklist: data/foo_blacklist.bed       #.bed-file containing blacklisted regions
  gtf: data/Astyanax_mexicanus.Astyanax_mexicanus-2.0.103_mod.gtf             #.gtf-file for annotation of peaks
  motifs: data/individual_motifs/*          #motifs (directory with files or individual files in MEME/JASPAR/PFM format)
  output: results_tobias                       #output directory 


#-------------------------------------------------------------------------#
#----------------------- Default module parameters -----------------------#
#-------------------------------------------------------------------------#

macs: "--nomodel --shift -100 --extsize 200 --broad"
atacorrect: ""
footprinting: ""
bindetect: ""
